coverage:
  status:
    project:
      default:
        # Coverage can drop by 0.1% without failing the status
        threshold: 0.1
    patch:
      default:
        target: 0

ignore:
  - "test/**/*"
  - "lib/**/*"

comment:
  require_changes: true

github_checks:
    annotations: false
