name: CI

on: [push]

env:
  CC: gcc-10
  CXX: g++-10
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install GCC 10
      shell: bash
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: ./build.sh -It

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -V -C $BUILD_TYPE
